Models/Event.cs
using System;

namespace YouthVolleyballHub.Models
{
    public class Event
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public string ContactEmail { get; set; }

        public EventCategory Category { get; set; }

        public int CategoryId { get; set; }

        public Organization Organization { get; set; }

        public int OrganizationId { get; set; }

        public int Id { get; set; }

        public Event(string name, string description, string contactEmail)
        {
            Name = name;
            Description = description;
            ContactEmail = contactEmail;
        }

        public Event()
        {
        }

        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object obj)
        {
            return obj is Event @event &&
            Id == @event.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }

}

Controllers/EventCategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using YouthVolleyballHub.Data;
using YouthVolleyballHub.Models;
using YouthVolleyballHub.ViewModels;

namespace YouthVolleyballHub.Controllers
{
    public class EventCategoryController : Controller
    {
        private ApplicationDbContext context;

        public EventCategoryController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            List<EventCategory> categories = context.Categories.ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            AddEventCategoryViewModel addEventCategoryViewModel = new AddEventCategoryViewModel();
            return View(addEventCategoryViewModel);
        }

        [HttpPost]
        public IActionResult ProcessCreateEventCategoryForm(AddEventCategoryViewModel addEventCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                EventCategory newCategory = new EventCategory
                {
                    Name = addEventCategoryViewModel.Name
                };

                context.Categories.Add(newCategory);
                context.SaveChanges();

                return Redirect("/EventCategory");
            }

            return View("Create", addEventCategoryViewModel);
        }
    }
}

Controllers/EventsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using YouthVolleyballHub.Data;
using YouthVolleyballHub.Models;
using YouthVolleyballHub.ViewModels;

namespace YouthVolleyballHub.Controllers
{
    public class EventsController : Controller
    {
        private ApplicationDbContext context;

        public EventsController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Event> events = context.Events
                .Include(e => e.Category)
                .ToList();

            return View(events);
        }

        [Authorize]
        public IActionResult Add()
        {

            List<Organization> organizations = context.Organizations.ToList(); 
            List<EventCategory> categories = context.Categories.ToList();
            
            AddEventViewModel addEventViewModel = new AddEventViewModel(organizations, categories);

            
            

            return View(addEventViewModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(AddEventViewModel addEventViewModel)
        {
            if (ModelState.IsValid)
            {
                EventCategory theCategory = context.Categories.Find(addEventViewModel.CategoryId);
                Organization theOrganization = context.Organizations.Find(addEventViewModel.OrganizationId);

                Event newEvent = new Event
                {
                    Name = addEventViewModel.Name,
                    Description = addEventViewModel.Description,
                    ContactEmail = addEventViewModel.ContactEmail,
                    Organization = theOrganization,
                    Category = theCategory
                };

                context.Events.Add(newEvent);
                context.SaveChanges();

                return Redirect("/Events");
            }

            return View(addEventViewModel);
        }

        [Authorize]
        public IActionResult Delete()
        {
            ViewBag.events = context.Events.ToList();

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int[] eventIds)
        {
            foreach (int eventId in eventIds)
            {
                Event theEvent = context.Events.Find(eventId);
                context.Events.Remove(theEvent);
            }

            context.SaveChanges();

            return Redirect("/Events");
        }

        public IActionResult Detail(int id)
        {
            Event theEvent = context.Events
               .Include(e => e.Category)
               .Single(e => e.Id == id);

            List<EventTag> eventTags = context.EventTags
                .Where(et => et.EventId == id)
                .Include(et => et.Tag)
                .ToList();

            EventDetailViewModel viewModel = new EventDetailViewModel(theEvent, eventTags);
            return View(viewModel);

        }
    }
}

Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using YouthVolleyballHub.Data;
using YouthVolleyballHub.Models;
using YouthVolleyballHub.ViewModels;

namespace YouthVolleyballHub.Controllers
{
    public class TagController : Controller
    {
        private ApplicationDbContext context;

        public TagController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Tag> tags = context.Tags.ToList();
            return View(tags);
        }

        public IActionResult Add()
        {
            Tag tag = new Tag();
            return View(tag);
        }

        [HttpPost]
        public IActionResult Add(Tag tag)
        {
            if (ModelState.IsValid)
            {
                context.Tags.Add(tag);
                context.SaveChanges();
                return Redirect("/Tag/");
            }

            return View("Add", tag);
        }

        public IActionResult AddEvent(int id)
        {
            Event theEvent = context.Events.Find(id);
            List<Tag> possibleTags = context.Tags.ToList();

            AddEventTagViewModel viewModel = new AddEventTagViewModel(theEvent, possibleTags);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddEvent(AddEventTagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                int eventId = viewModel.EventId;
                int tagId = viewModel.TagId;

                EventTag eventTag = new EventTag
                {
                    EventId = eventId,
                    TagId = tagId
                };

                context.EventTags.Add(eventTag);
                context.SaveChanges();

                return Redirect("/Events/Detail/" + eventId);
            }

            return View(viewModel);
        }
    }
}

Views/Events/Add.cshtml
@model YouthVolleyballHub.ViewModels.AddEventViewModel;

<h1>Add Event</h1>

<form asp-controller="Events" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Contact Email</label>
        <input asp-for="ContactEmail" />
    </div>
    <div class="form-group">
        <label asp-for="OrganizationId">Organization</label>
        <select asp-for="OrganizationId" asp-items="Model.Organizations"></select>
    </div>
    <p>To add your organization<a style="display:inline" asp-area="Identity" asp-page="/Account/Register"> register a new account here</a></p>
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="Model.Categories"></select>
    </div>
    <p>Don't see the category you're looking for?</p>
    <p><a style="display:inline" asp-area="" asp-controller="EventCategory" asp-action="Create">click here to add a category</a></p>
    <input type="submit" value="Add Event" />
</form>

Views/Events/Delete.cshtml
<h1>Delete Event</h1>

<form method="post">
    @foreach (var evt in ViewBag.events)
    {
        <div class="form-group">
            <label>
                <span>@evt.Name</span>
                <input type="checkbox" name="eventIds" value="@evt.Id" class="form-control">
            </label>
        </div>
    }

    <input type="submit" value="Delete Selected Events" class="btn btn-danger">

</form>

Views/Events/Detail.cshtml
@model YouthVolleyballHub.ViewModels.EventDetailViewModel

<h1>@Model.Name</h1>

<table class="table">
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <th>Contact Email</th>
        <td>@Model.ContactEmail</td>
    </tr>
    <tr>
        <th>Category</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>@Model.TagText</td>
    </tr>

</table>

<a asp-controller="Tag" asp-action="AddEvent" asp-route-id="@Model.EventId">Add Tag</a>

Views/Events/EventsByOrganization.cshtml
@*
    todo: create a view that lists an idividual organizations events
*@

Views/Events/Index.cshtml
@model List<YouthVolleyballHub.Models.Event>

<h1>Volleyball Events</h1><br />

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>

<p>
    <a asp-controller="Events" asp-action="Delete">Delete Event</a>
</p><br />

@if (Model.Count == 0)
{
    <p>No events yet!</p>
}
else
{
    
    //<div class="card-columns">
    <div class="row">
    @foreach (var evt in Model)
    {
        <div class="col-md-4">
            <div class="card" style="width: 100%;">
                <img class="card-img" src="https://img.freepik.com/free-photo/medium-shot-teacher-holding-clipboard_23-2149038821.jpg" alt="Event Image">
                <div class="card-body">
                    <h5 class="card-title"><a asp-controller="Events" asp-action="Detail" asp-route-id="@evt.Id">@evt.Name</a></h5>
                    <p class="card-text">@evt.Description</p>
                    <p class="card-text"><strong>Contact Email:</strong> @evt.ContactEmail</p>
                    <p class="card-text"><strong>Category:</strong> @evt.Category.Name</p>
                </div>
            </div>
        </div>
    }
    </div>

    
    
    @*<table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Contact Email
            </th>
            <th>
                Category
            </th>
        </tr>
        @foreach (var evt in Model)
        {
            <tr>
                <td><a asp-controller="Events" asp-action="Detail" asp-route-id="@evt.Id">@evt.Name</a></td>
                <td>@evt.Description</td>
                <td>@evt.ContactEmail</td>
                <td>@evt.Category.Name</td>
            </tr>
        }
    </table>*@
}