Models/Organization.cs
using System;
using System.Collections.Generic;

namespace YouthVolleyballHub.Models
{
    public class Organization
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public string ContactEmail { get; set; }

        public int Id { get; set; }

        public List<Event> events { get; set; }

        public Organization(string name, string description, string contactEmail)
        {
            Name = name;
            Description = description;
            ContactEmail = contactEmail;
        }

        public Organization()
        {
        }

        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object obj)
        {
            return obj is Organization @organization &&
            Id == @organization.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

Controllers/OrganizationsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using YouthVolleyballHub.Data;
using YouthVolleyballHub.Models;
using YouthVolleyballHub.ViewModels;

namespace YouthVolleyballHub.Controllers
{
    public class OrganizationsController : Controller
    {
        private ApplicationDbContext context;

        public OrganizationsController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Organization> organizations = context.Organizations.ToList();

            return View(organizations);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddOrganizationViewModel addOrganizationViewModel)
        {
            if (ModelState.IsValid)
            {

                Organization newOrganization = new Organization
                {
                    Name = addOrganizationViewModel.Name,
                    Description = addOrganizationViewModel.Description,
                    ContactEmail = addOrganizationViewModel.ContactEmail
                };

                context.Organizations.Add(newOrganization);
                context.SaveChanges();


                // not sure I want to redirect to this page
                return Redirect("/Organizations");
            }

            return View(addOrganizationViewModel);
        }
    }
}

Views/Organizations/Add.cshtml
@model YouthVolleyballHub.ViewModels.AddOrganizationViewModel;

<h1>Add Your Organization</h1>

<form asp-controller="Organizations" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Contact Email</label>
        <input asp-for="ContactEmail" />
    </div>
    
    <input type="submit" value="Add Organization" />
</form>

Views/Organizations/Index.cshtml
@model List<YouthVolleyballHub.Models.Organization>

<h1>Youth Volleyball Organizations</h1>

@if (Model.Count == 0)
{
    <p>No organizations have been created yet</p>
}
else
{
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Contact Email
            </th>
        </tr>
        @foreach (var org in Model)
        {
            <tr>
                @*<td><a asp-controller="Organizations" asp-action="Detail" asp-route-id="@org.Id">@org.Name</a></td>*@
                <td>@org.Name</td>
                <td>@org.Description</td>
                <td>@org.ContactEmail</td>
            </tr>
        }
    </table>
}